Added checks and added directions for new users (help)
I'm sorry for this kind of commit changes modt of lines in project. But it is
still same in the proinciples.

diff --git a/guest-create b/guest-create
--- a/guest-create
+++ b/guest-create
@@ -1,58 +1,75 @@
 #!/bin/bash
-
-# exit on first error
 set -e
 . /etc/simplelxc
+. $BIN_DIR/functions
+
+state=init
+
+# backup stdout and stderr
+exec 3>&1 4>&2
 
 function usage {
-	echo "usage: ${0##*/} name <guestname> <ip> [<template>]"
+	echo "usage: $(get_sl_command) create <guestname> [<ip>] [<template>]"
 }
 
 function show_error {
-	echo -e "${0##*/}: \E[31m$1" >&2
-	tput sgr0 >&2
-	usage >&2
+	color_echo RED "$1" >&4
+	usage >&4
 	exit 2
 }
 
-# copied from http://www.linuxjournal.com/content/validating-ip-address-bash-script
-function valid_ip {
-	local  ip=$1
-	local  stat=1
-	if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
-		OIFS=$IFS
-		IFS='.'
-		ip=($ip)
-		IFS=$OIFS
-		[[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
-			&& ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
-		stat=$?
+function error_trap {
+	color_echo RED "Program terminated, guest is not created" >&4
+	if [ "$state" != "init" -o "$state" != "checks" -o "$state" != "finished" ]; then
+		if [ -n "$lxchostname" ]; then
+			rm -rf --preserve-root $LXCS_DIR/$lxchostname
+		fi
 	fi
-	return $stat
+	exit 2
 }
 
-if [[ "$EUID" -ne 0 ]]; then
-	show_error "You must be root to run this script. (Hint: use sudo)"
-fi
+trap error_trap TERM INT
 
-# TODO: first parameter is hostname but second parameter could be an ip address
-#       or a template name, check if it is a valid ip or else search a template
-#       with that name, this is a bit tricky but most simple way for users
-lxchostname=${1:-undefined}
-ipaddr=${2:-undefined}
-template_name=${3:-$DEFAULT_TEMPLATE}
+state=checks
 
-# TODO: assign an empty ip address from network, must not be assigned to any
-#       where and must not be used by any closed guest's.
+lxchostname=$1
 
-template_dir=$TEMPLATES_DIR/$template_name
-
-if [ "$lxchostname" == "undefined" ]; then
+if [ -z "$lxchostname" ]; then
 	show_error "You must give a guestname."
 fi
 
-if [ "$ipaddr" == "undefined" ]; then
-	show_error "You must give an IP address."
+if is_guest "$lxchostname"; then
+	show_error "Guest '$lxchostname' already exists."
+fi
+
+if test -e "$LXCS_DIR/$lxchostname"; then
+	show_error "Guest target already exists: $LXCS_DIR/$lxchostname"
+fi
+
+# second parameter could be an ip address or a template name, check if
+# it is a valid ip or else search for a template with that name, this
+# is a bit tricky but one of the simplest ways for users
+second_param=$2
+if [ -n "$second_param" ]; then
+	if ! valid_ip "$second_param"; then
+		if ! is_template "$second_param"; then
+			show_error "Given '$second_param' is not an IP address nor a template."
+		fi
+		template_name=${second_param:-$DEFAULT_TEMPLATE}
+	else
+		ipaddr=$second_param
+		template_name=${3:-$DEFAULT_TEMPLATE}
+	fi
+else
+	color_echo YELLOW "Chosen default template '$DEFAULT_TEMPLATE' as template"
+	template_name=$DEFAULT_TEMPLATE
+fi
+
+template_dir=$TEMPLATES_DIR/$template_name
+
+if [ -z "$ipaddr" ]; then
+	ipaddr=$(get_next_suitible_ip)
+	color_echo YELLOW "Chosen $ipaddr as guest IP address"
 fi
 
 if ! valid_ip "$ipaddr"; then
@@ -63,7 +80,7 @@ if host "$lxchostname" | grep --color -C10 'has address' ; then
 	show_error "Given name ($lxchostname) is in use."
 fi
 
-if ping -c 2 -w 4 "$ipaddr" &>/dev/null; then
+if check_ping "$ipaddr"; then
 	show_error "Given ip address ($ipaddr) is in use."
 fi
 
@@ -71,36 +88,27 @@ if ! $BIN_DIR/host-check &>/dev/null; then
 	$BIN_DIR/host-prepare
 fi
 
-if ! test -d "$template_dir" -a "$template_name" == "$DEFAULT_TEMPLATE"; then
-	$BIN_DIR/template-create "$template_name" "$template_name"
+if [ "$template_name" == "$DEFAULT_TEMPLATE" ]; then
+	if ! is_template "$DEFAULT_TEMPLATE"; then
+		color_echo YELLOW "Creating new template '$template_name'"
+		$BIN_DIR/template-create "$template_name" "$template_name"
+	fi
 fi
 
-if ! test -d "$template_dir"; then
-	show_error "Template ($template_dir) not exists."
+if ! is_template "$template_name"; then
+	show_error "Template ($template_name) not exists."
 fi
 
-## Fixed: mac addresses may be conflict, we should check if it exist
-#mac=00:FF:12:34:$(echo $ipaddr | tr -d '.' | sed 's/^.*\(..\)\(..\)$/\1:\2/')
-# TODO: What if we change a machines IP address later and use that ip in an other machine
-mac=$(printf "02:00:%x:%x:%x:%x" ${ipaddr//./ })
+# TODO: Next line generates same mac address for a given ip
+#       address.What if we change a machines IP address manually and
+#       then try to use old ip in an other machine.
+mac=$(printf "02:00:%02x:%02x:%02x:%02x" ${ipaddr//./ })
 lxc_dir=$LXCS_DIR/$lxchostname
 rootfs=$lxc_dir/rootfs
 config=$lxc_dir/config
 
-echo -e "\E[31m===== variables start ====="; tput sgr0
-cat <<EOS
-name		$lxchostname
-template	$template_dir
-rootfs		$rootfs/
-config		$config
-macaddr		$mac
-ip		$ipaddr
-network		$NETWORK
-gateway		$HOST_IP
-EOS
-echo -e "\E[31m====== variables end ======"; tput sgr0
-
-exec 3>&1 4>&2 >>/var/log/simplelxc 2>&1
+#echo "Logging into /var/log/simplelxc"
+exec >>/var/log/simplelxc 2>&1
 echo "================================================================================"
 echo "$(date +%F\ %T): Running: $0 $@"
 
@@ -108,16 +116,20 @@ export LANGUAGE=C
 export LC_ALL=C
 export LANG=C
 
+state=template_copy
+echo "Creating root file system..." >&3
 # create lxc guest system root
 mkdir $lxc_dir
 cp -apr $template_dir $rootfs
 
+state=configure_guest
+echo "Configuring guest..." >&3
 sed -i "s/template-$template_name/$lxchostname/g" $(grep -rl "template-$template_name" $rootfs/etc/ 2>/dev/null)
 sed -i "s/127.0.0.2/$ipaddr/g" $(grep -rl "127.0.0.2" $rootfs/etc/ 2>/dev/null)
 
 # remove precreated keys in the template and regenerate them
 rm -f $rootfs/etc/ssh/ssh_host_*
-chroot $rootfs dpkg-reconfigure openssh-server 
+chroot $rootfs dpkg-reconfigure openssh-server
 
 # create interface file
 cat <<EOS > $rootfs/etc/network/interfaces
@@ -154,8 +166,8 @@ lxc.cgroup.devices.allow = c 254:0 rwm
 lxc.mount.entry=proc $rootfs/proc proc nodev,noexec,nosuid 0 0
 lxc.mount.entry=devpts $rootfs/dev/pts devpts defaults 0 0
 lxc.mount.entry=sysfs $rootfs/sys sysfs defaults  0 0
-lxc.mount.entry=tmpfs $rootfs/var/lock tmpfs defaults 0 0
-lxc.mount.entry=tmpfs $rootfs/var/run tmpfs defaults 0 0
+#lxc.mount.entry=tmpfs $rootfs/var/lock tmpfs defaults 0 0
+#lxc.mount.entry=tmpfs $rootfs/var/run tmpfs defaults 0 0
 
 # You can enable these lines if you want your user and home directory in this LXC
 # But if you do that, you cant add/remove user inside LXC, gor example you cant
@@ -177,7 +189,7 @@ EOS
 
 sed -i "/^CONTAINERS=/s/CONTAINERS=\"\(.*\)\"/CONTAINERS=\" \1 $lxchostname\"/" /etc/default/lxc
 ln -s $config /etc/lxc/$lxchostname.conf | :
-
+state=put_keys
 # put host key to guest
 tmp_umask=$(umask)
 umask 077
@@ -189,9 +201,16 @@ echo "$(date +%F\ %T): Finished: $0 $@"
 echo "================================================================================"
 
 exec 1>&3 2>&4
-echo "Created guest: $lxchostname"
+state=finished
+color_echo GREEN "Created new guest '$lxchostname'"
 
-# start guest and log in to it
-echo "You can start and login to the guest using theese"
-echo ">>> sudo sl start $lxchostname"
-echo ">>> sudo sl login $lxchostname"
+# if there is any open file descriptor before calling lxc-start, it
+# fails to start container, so we close our fd's before starting the guest
+exec 3>&- 4>&-
+
+echo "You can list the information about guest by
+>>> $(get_sl_command) info $lxchostname"
+
+# start guest immediately
+$BIN_DIR/guest-start "$lxchostname"
+
